name: Generate Store Files

on:
  push:
    paths:
      - 'scripts/metadata.json'
      - 'scripts/template.json'
      - 'scripts/generate.sh'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq libplist-utils
          
      - name: Generate store files
        working-directory: ./scripts
        run: |
          chmod +x generate.sh
          ./generate.sh

      - name: Commit changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ../*.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update store files [skip ci]"
          git push
