name: Generate Store Files

on:
  push:
    paths:
      - 'scripts/metadata.json'
      - 'scripts/template.json'
      - 'scripts/generate.sh'
  workflow_dispatch:

jobs:
  generate:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate files
        working-directory: ./scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x generate.sh
          ./generate.sh

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.json
          echo "Staged files:"
          git diff --staged --name-only
          git diff --quiet && git diff --staged --quiet || git commit -m "Update store files"
          git push
